apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-java-cloud-native
spec:
  params:
  - name: build-type
    type: string
    description: "Selected build type: quarkus-jvm, quarkus-fast-jar, quarkus-native, spring-boot"
  - name: git-repo-url
    type: string
    description: "Git Repository URL"
  - name: git-checkout-sha
    type: string
    description: "Git SHA to checkout"
    default: "main"
  - name: config-git-path
    type: string
    description: "Config Git Path"
    default: "/deploy-config"
  tasks:
  - name: build
    taskRef:
      name: build-java-cloud-native
    params:
    - name: build-type
      value: $(params.build-type)
    - name: git-repo-url
      value: $(params.git-repo-url)
    - name: git-checkout-sha
      value: $(params.git-checkout-sha)
  - name: deploy
    taskRef:
      name: deploy-app
    runAfter:
    - build
    params:
    - name: app-name
      value: $(params.app-name)
    - name: git-repo-url
      value: $(params.git-repo-url)
    - name: git-checkout-sha
      value: $(params.git-checkout-sha)
    - name: config-git-path
      value: $(params.config-git-path)
