apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  params:
  - name: app-name
    description: the application name
  steps:
  - name: rollout
    image: image-registry.openshift-image-registry.svc:5000/openshift/origin-cli:latest
    imagePullPolicy: IfNotPresent
    workingDir: /workspace
    script: |
      echo Rolling out $(params.app-name)
      oc rollout restart deployment/$(params.app-name)
      echo -----------------------------------