apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-app
spec:
  params:
  - name: git-repo-url
    type: string
    description: "Git Repository URL"
  - name: git-branch
    type: string
    description: "Git Branch to monitor"
    default: "main"
  - name: build-type
    type: string
    description: "Selected build type: quarkus-jvm, quarkus-fast-jar, quarkus-native, spring-boot"
    default: "main"
  steps:
  - name: create-app
    image: image-registry.openshift-image-registry.svc:5000/openshift/origin-cli:latest
    imagePullPolicy: IfNotPresent
    workingDir: /workspace
    script: |
      echo "Creating Application Resources"
      APP_NAME=$(basename $(params.git-repo-url) | cut -d'.' -f1)
      oc process --local -f /workspace/templates/app-resources-template.yaml -p APP_NAME=${APP_NAME} -p GIT_REPOSITORY=$(params.git-repo-url) -p GIT_BRANCH=$(params.git-branch) -p BUILD_TYPE=$(params.build-type)| oc apply -f -
    volumeMounts:
    - name: app-resources-template
      mountPath: /workspace/templates
  volumes:
  - name: app-resources-template
    configMap:
      name: app-resources-template