apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-java-cloud-native
spec:
  params:
  - name: app-name
    type: string
    description: "Application Name"
  - name: build-type
    type: string
    description: "Selected build type: quarkus-jvm, quarkus-fast-jar, quarkus-native, spring-boot"
  - name: git-repo-url
    type: string
    description: "Git Repository URL"
  - name: git-checkout-sha
    type: string
    description: "Git SHA to checkout"
    default: "main"
  - name: config-git-repo-url
    type: string
    description: "Config Git Repository URL"
  - name: config-git-branch
    type: string
    description: "Config Git Branch to clone"
    default: "main"
  - name: config-git-path
    type: string
    description: "Config Git Path"
    default: "/"
  tasks:
  - name: build
    taskRef:
      name: build-java-cloud-native
    params:
    - name: app-name
      value: $(params.app-name)
    - name: build-type
      value: $(params.build-type)
    - name: git-repo-url
      value: $(params.git-repo-url)
    - name: git-checkout-sha
      value: $(params.git-checkout-sha)
  - name: config
    taskRef:
      name: config-app
    runAfter:
    - build
    params:
    - name: app-name
      value: $(params.app-name)
    - name: config-git-repo-url
      value: $(params.config-git-repo-url)
    - name: config-git-branch
      value: $(params.config-git-branch)
    - name: config-git-path
      value: $(params.config-git-path)
  - name: deploy
    taskRef:
      name: deploy-app
    runAfter:
    - config
    params:
    - name: app-name
      value: $(params.app-name)