apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: "Build and Deploy template for Quarkus applications built using a Tekton Pipeline."
    iconClass: icon-openjdk
    openshift.io/display-name: "Quarkus Fast-Jar Build & Deploy Pipeline for DEV - Branch Build"
    template.openshift.io/bindable: "false"
    tags: "java,quarkus"
    version: "1.0"
  name: create-simple-rolling-replace-quarkus-fast-jar-app
objects:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: ${APP_NAME}-pipeline
    spec:
      serviceAccountName: pipeline
      pipelineRef: 
        name: build-and-deploy-java
      params:
      - name: build-type
        value: quarkus-fast-jar
      - name: deploy-type
        value: rolling-replace
      - name: git-repo-url
        value: ${GIT_REPOSITORY}
      - name: git-checkout
        value: ${GIT_BRANCH}
      - name: clone-type
        value: branch
      - name: config-git-path
        value: deploy-config

parameters:
  -
    description: "Git repository for source code"
    displayName: "Git Repo"
    name: GIT_REPOSITORY
    required: true
  -
    description: "Git repository branch to build app from"
    displayName: "Git Branch"
    name: GIT_BRANCH
    required: true
    value: "main"
  - 
    description: "App Name"
    displayName: "Application Name"
    name: APP_NAME
    required: true
    
