apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Build and Deploy template for Spring Boot applications built using a Tekton Pipeline."
    iconClass: icon-openjdk
    openshift.io/display-name: "Spring Boot JVM Build & Deploy Pipeline for DEV - GitLab"
    template.openshift.io/bindable: "false"
    tags: "java,quarkus"
    version: "1.0"
  name: create-app
objects:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: create-app-${RANDOM_TASK}
    spec:
      taskRef:
        name: create-app
      params:
      - name: git-repo-url
        value: ${GIT_REPOSITORY}
      - name: git-branch
        value: ${GIT_BRANCH}
      - name: build-type
        value: spring-boot

parameters:
  -
    description: "Git repository for source code"
    displayName: "Git Repo"
    name: GIT_REPOSITORY
    required: true
  -
    description: "Git repository branch to build app from"
    displayName: "Git Branch"
    name: GIT_BRANCH
    required: true
    value: "main"
  - 
    description: "auto-filled random task name"
    displayName: "Auto-Filled (Leave this field blank)"
    name: RANDOM_TASK
    generate: expression
    from: "[a-z0-9]{8}"
